# Historical official Education balance transcribed from estatisticas.xlsx.
HISTORICAL_BASELINE = {
    2011: {
        'ACTION - A\xe7\xe3o Social': 0,
        'ACTION - Bares': 0,
        'ACTION - Empresa': 25,
        'ACTION - Escola': 52,
        'ACTION - Eventos': 0,
        'ACTION - Fiscaliza\xe7\xe3o': 0,
        'ACTION - Geral': 0,
        'ACTION - Outros': 0,
        'ACTION - Ped\xe1gio': 0,
        'ACTION - Pontos tur\xedsticos': 0,
        'ACTION - Praia': 0,
        'ACTION - Pra\xe7as Esportivas': 0,
        'ACTION - Pra\xe7as/Parques P\xfablicos': 0,
        'ACTION - Shopping': 0,
        'ACTION - Universidade': 9,
        'AUDIENCE - ACOES': 0,
        'AUDIENCE - Geral': 766996,
        'AUDIENCE - PALESTRAS': 0,
        'LECTURES - Geral': 86,
        'MATERIAL - Certificados': 6100,
        'MATERIAL - Geral': 0,
        'MATERIAL - Soprinho': 0,
    },
    2012: {
        'ACTION - A\xe7\xe3o Social': 0,
        'ACTION - Bares': 0,
        'ACTION - Empresa': 111,
        'ACTION - Escola': 96,
        'ACTION - Eventos': 0,
        'ACTION - Fiscaliza\xe7\xe3o': 0,
        'ACTION - Geral': 0,
        'ACTION - Outros': 0,
        'ACTION - Ped\xe1gio': 0,
        'ACTION - Pontos tur\xedsticos': 0,
        'ACTION - Praia': 0,
        'ACTION - Pra\xe7as Esportivas': 0,
        'ACTION - Pra\xe7as/Parques P\xfablicos': 0,
        'ACTION - Shopping': 0,
        'ACTION - Universidade': 13,
        'AUDIENCE - ACOES': 0,
        'AUDIENCE - Geral': 2925411,
        'AUDIENCE - PALESTRAS': 0,
        'LECTURES - Geral': 220,
        'MATERIAL - Certificados': 19785,
        'MATERIAL - Geral': 0,
        'MATERIAL - Soprinho': 0,
    },
    2013: {
        'ACTION - A\xe7\xe3o Social': 0,
        'ACTION - Bares': 0,
        'ACTION - Empresa': 273,
        'ACTION - Escola': 132,
        'ACTION - Eventos': 0,
        'ACTION - Fiscaliza\xe7\xe3o': 0,
        'ACTION - Geral': 0,
        'ACTION - Outros': 0,
        'ACTION - Ped\xe1gio': 0,
        'ACTION - Pontos tur\xedsticos': 0,
        'ACTION - Praia': 0,
        'ACTION - Pra\xe7as Esportivas': 0,
        'ACTION - Pra\xe7as/Parques P\xfablicos': 0,
        'ACTION - Shopping': 0,
        'ACTION - Universidade': 24,
        'AUDIENCE - ACOES': 0,
        'AUDIENCE - Geral': 3138812,
        'AUDIENCE - PALESTRAS': 0,
        'LECTURES - Geral': 429,
        'MATERIAL - Certificados': 35464,
        'MATERIAL - Geral': 0,
        'MATERIAL - Soprinho': 0,
    },
    2014: {
        'ACTION - A\xe7\xe3o Social': 0,
        'ACTION - Bares': 0,
        'ACTION - Empresa': 281,
        'ACTION - Escola': 211,
        'ACTION - Eventos': 0,
        'ACTION - Fiscaliza\xe7\xe3o': 0,
        'ACTION - Geral': 0,
        'ACTION - Outros': 0,
        'ACTION - Ped\xe1gio': 0,
        'ACTION - Pontos tur\xedsticos': 0,
        'ACTION - Praia': 0,
        'ACTION - Pra\xe7as Esportivas': 0,
        'ACTION - Pra\xe7as/Parques P\xfablicos': 0,
        'ACTION - Shopping': 0,
        'ACTION - Universidade': 28,
        'AUDIENCE - ACOES': 0,
        'AUDIENCE - Geral': 2546749,
        'AUDIENCE - PALESTRAS': 0,
        'LECTURES - Geral': 520,
        'MATERIAL - Certificados': 35022,
        'MATERIAL - Geral': 0,
        'MATERIAL - Soprinho': 12298,
    },
    2015: {
        'ACTION - A\xe7\xe3o Social': 0,
        'ACTION - Bares': 0,
        'ACTION - Empresa': 236,
        'ACTION - Escola': 91,
        'ACTION - Eventos': 0,
        'ACTION - Fiscaliza\xe7\xe3o': 0,
        'ACTION - Geral': 0,
        'ACTION - Outros': 0,
        'ACTION - Ped\xe1gio': 0,
        'ACTION - Pontos tur\xedsticos': 0,
        'ACTION - Praia': 0,
        'ACTION - Pra\xe7as Esportivas': 0,
        'ACTION - Pra\xe7as/Parques P\xfablicos': 0,
        'ACTION - Shopping': 0,
        'ACTION - Universidade': 8,
        'AUDIENCE - ACOES': 0,
        'AUDIENCE - Geral': 601500,
        'AUDIENCE - PALESTRAS': 0,
        'LECTURES - Geral': 335,
        'MATERIAL - Certificados': 21434,
        'MATERIAL - Geral': 0,
        'MATERIAL - Soprinho': 4995,
    },
    2016: {
        'ACTION - A\xe7\xe3o Social': 0,
        'ACTION - Bares': 0,
        'ACTION - Empresa': 159,
        'ACTION - Escola': 67,
        'ACTION - Eventos': 0,
        'ACTION - Fiscaliza\xe7\xe3o': 0,
        'ACTION - Geral': 0,
        'ACTION - Outros': 0,
        'ACTION - Ped\xe1gio': 0,
        'ACTION - Pontos tur\xedsticos': 0,
        'ACTION - Praia': 0,
        'ACTION - Pra\xe7as Esportivas': 0,
        'ACTION - Pra\xe7as/Parques P\xfablicos': 0,
        'ACTION - Shopping': 0,
        'ACTION - Universidade': 3,
        'AUDIENCE - ACOES': 0,
        'AUDIENCE - Geral': 157133,
        'AUDIENCE - PALESTRAS': 0,
        'LECTURES - Geral': 229,
        'MATERIAL - Certificados': 13091,
        'MATERIAL - Geral': 0,
        'MATERIAL - Soprinho': 22398,
    },
    2017: {
        'ACTION - A\xe7\xe3o Social': 0,
        'ACTION - Bares': 0,
        'ACTION - Empresa': 223,
        'ACTION - Escola': 118,
        'ACTION - Eventos': 0,
        'ACTION - Fiscaliza\xe7\xe3o': 0,
        'ACTION - Geral': 0,
        'ACTION - Outros': 0,
        'ACTION - Ped\xe1gio': 0,
        'ACTION - Pontos tur\xedsticos': 0,
        'ACTION - Praia': 0,
        'ACTION - Pra\xe7as Esportivas': 0,
        'ACTION - Pra\xe7as/Parques P\xfablicos': 0,
        'ACTION - Shopping': 0,
        'ACTION - Universidade': 5,
        'AUDIENCE - ACOES': 0,
        'AUDIENCE - Geral': 131029,
        'AUDIENCE - PALESTRAS': 0,
        'LECTURES - Geral': 346,
        'MATERIAL - Certificados': 200,
        'MATERIAL - Geral': 0,
        'MATERIAL - Soprinho': 30638,
    },
    2018: {
        'ACTION - A\xe7\xe3o Social': 0,
        'ACTION - Bares': 0,
        'ACTION - Empresa': 209,
        'ACTION - Escola': 96,
        'ACTION - Eventos': 0,
        'ACTION - Fiscaliza\xe7\xe3o': 0,
        'ACTION - Geral': 726,
        'ACTION - Outros': 0,
        'ACTION - Ped\xe1gio': 0,
        'ACTION - Pontos tur\xedsticos': 0,
        'ACTION - Praia': 0,
        'ACTION - Pra\xe7as Esportivas': 0,
        'ACTION - Pra\xe7as/Parques P\xfablicos': 0,
        'ACTION - Shopping': 0,
        'ACTION - Universidade': 5,
        'AUDIENCE - ACOES': 0,
        'AUDIENCE - Geral': 152261,
        'AUDIENCE - PALESTRAS': 0,
        'LECTURES - Geral': 310,
        'MATERIAL - Certificados': 25365,
        'MATERIAL - Geral': 0,
        'MATERIAL - Soprinho': 2016767,
    },
    2019: {
        'ACTION - A\xe7\xe3o Social': 4,
        'ACTION - Bares': 299,
        'ACTION - Empresa': 296,
        'ACTION - Escola': 154,
        'ACTION - Eventos': 239,
        'ACTION - Fiscaliza\xe7\xe3o': 0,
        'ACTION - Geral': 818,
        'ACTION - Outros': 191,
        'ACTION - Ped\xe1gio': 13,
        'ACTION - Pontos tur\xedsticos': 0,
        'ACTION - Praia': 0,
        'ACTION - Pra\xe7as Esportivas': 65,
        'ACTION - Pra\xe7as/Parques P\xfablicos': 0,
        'ACTION - Shopping': 7,
        'ACTION - Universidade': 13,
        'AUDIENCE - ACOES': 149804,
        'AUDIENCE - Geral': 201003,
        'AUDIENCE - PALESTRAS': 51199,
        'LECTURES - Geral': 463,
        'MATERIAL - Certificados': 15572,
        'MATERIAL - Geral': 8989409,
        'MATERIAL - Soprinho': 29615,
    },
    2020: {
        'ACTION - A\xe7\xe3o Social': 428,
        'ACTION - Bares': 36,
        'ACTION - Empresa': 40,
        'ACTION - Escola': 5,
        'ACTION - Eventos': 35,
        'ACTION - Fiscaliza\xe7\xe3o': 0,
        'ACTION - Geral': 945,
        'ACTION - Outros': 426,
        'ACTION - Ped\xe1gio': 0,
        'ACTION - Pontos tur\xedsticos': 0,
        'ACTION - Praia': 0,
        'ACTION - Pra\xe7as Esportivas': 12,
        'ACTION - Pra\xe7as/Parques P\xfablicos': 0,
        'ACTION - Shopping': 8,
        'ACTION - Universidade': 1,
        'AUDIENCE - ACOES': 51751,
        'AUDIENCE - Geral': 51460,
        'AUDIENCE - PALESTRAS': 3674,
        'LECTURES - Geral': 46,
        'MATERIAL - Certificados': 0,
        'MATERIAL - Geral': 111802,
        'MATERIAL - Soprinho': 2190,
    },
    2021: {
        'ACTION - A\xe7\xe3o Social': 4,
        'ACTION - Bares': 31,
        'ACTION - Empresa': 89,
        'ACTION - Escola': 24,
        'ACTION - Eventos': 16,
        'ACTION - Fiscaliza\xe7\xe3o': 0,
        'ACTION - Geral': 673,
        'ACTION - Outros': 585,
        'ACTION - Ped\xe1gio': 7,
        'ACTION - Pontos tur\xedsticos': 0,
        'ACTION - Praia': 10,
        'ACTION - Pra\xe7as Esportivas': 0,
        'ACTION - Pra\xe7as/Parques P\xfablicos': 0,
        'ACTION - Shopping': 20,
        'ACTION - Universidade': 0,
        'AUDIENCE - ACOES': 64270,
        'AUDIENCE - Geral': 70535,
        'AUDIENCE - PALESTRAS': 6265,
        'LECTURES - Geral': 113,
        'MATERIAL - Certificados': 0,
        'MATERIAL - Geral': 49880,
        'MATERIAL - Soprinho': 9094,
    },
    2022: {
        'ACTION - A\xe7\xe3o Social': 6,
        'ACTION - Bares': 32,
        'ACTION - Empresa': 82,
        'ACTION - Escola': 274,
        'ACTION - Eventos': 40,
        'ACTION - Fiscaliza\xe7\xe3o': 0,
        'ACTION - Geral': 963,
        'ACTION - Outros': 802,
        'ACTION - Ped\xe1gio': 8,
        'ACTION - Pontos tur\xedsticos': 0,
        'ACTION - Praia': 61,
        'ACTION - Pra\xe7as Esportivas': 8,
        'ACTION - Pra\xe7as/Parques P\xfablicos': 0,
        'ACTION - Shopping': 6,
        'ACTION - Universidade': 8,
        'AUDIENCE - ACOES': 74319,
        'AUDIENCE - Geral': 113930,
        'AUDIENCE - PALESTRAS': 39611,
        'LECTURES - Geral': 364,
        'MATERIAL - Certificados': 0,
        'MATERIAL - Geral': 44137,
        'MATERIAL - Soprinho': 24114,
    },
    2023: {
        'ACTION - A\xe7\xe3o Social': 1,
        'ACTION - Bares': 193,
        'ACTION - Empresa': 121,
        'ACTION - Escola': 261,
        'ACTION - Eventos': 101,
        'ACTION - Fiscaliza\xe7\xe3o': 0,
        'ACTION - Geral': 1193,
        'ACTION - Outros': 780,
        'ACTION - Ped\xe1gio': 12,
        'ACTION - Pontos tur\xedsticos': 0,
        'ACTION - Praia': 16,
        'ACTION - Pra\xe7as Esportivas': 80,
        'ACTION - Pra\xe7as/Parques P\xfablicos': 0,
        'ACTION - Shopping': 10,
        'ACTION - Universidade': 5,
        'AUDIENCE - ACOES': 157409,
        'AUDIENCE - Geral': 199068,
        'AUDIENCE - PALESTRAS': 41659,
        'LECTURES - Geral': 387,
        'MATERIAL - Certificados': 9273,
        'MATERIAL - Geral': 144115,
        'MATERIAL - Soprinho': 11681,
    },
    2024: {
        'ACTION - A\xe7\xe3o Social': 0,
        'ACTION - Bares': 176,
        'ACTION - Empresa': 148,
        'ACTION - Escola': 248,
        'ACTION - Eventos': 239,
        'ACTION - Fiscaliza\xe7\xe3o': 0,
        'ACTION - Geral': 1386,
        'ACTION - Outros': 890,
        'ACTION - Ped\xe1gio': 5,
        'ACTION - Pontos tur\xedsticos': 0,
        'ACTION - Praia': 53,
        'ACTION - Pra\xe7as Esportivas': 3,
        'ACTION - Pra\xe7as/Parques P\xfablicos': 0,
        'ACTION - Shopping': 20,
        'ACTION - Universidade': 6,
        'AUDIENCE - ACOES': 157626,
        'AUDIENCE - Geral': 190861,
        'AUDIENCE - PALESTRAS': 33235,
        'LECTURES - Geral': 402,
        'MATERIAL - Certificados': 0,
        'MATERIAL - Geral': 112920,
        'MATERIAL - Soprinho': 553,
    },
    2025: {
        'ACTION - A\xe7\xe3o Social': 3,
        'ACTION - Bares': 207,
        'ACTION - Empresa': 155,
        'ACTION - Escola': 296,
        'ACTION - Eventos': 195,
        'ACTION - Fiscaliza\xe7\xe3o': 0,
        'ACTION - Geral': 1541,
        'ACTION - Outros': 1014,
        'ACTION - Ped\xe1gio': 4,
        'ACTION - Pontos tur\xedsticos': 0,
        'ACTION - Praia': 68,
        'ACTION - Pra\xe7as Esportivas': 10,
        'ACTION - Pra\xe7as/Parques P\xfablicos': 0,
        'ACTION - Shopping': 40,
        'ACTION - Universidade': 3,
        'AUDIENCE - ACOES': 165603,
        'AUDIENCE - Geral': 207964,
        'AUDIENCE - PALESTRAS': 42361,
        'LECTURES - Geral': 454,
        'MATERIAL - Certificados': 10,
        'MATERIAL - Geral': 39125,
        'MATERIAL - Soprinho': 50,
    },
    2026: {
        'ACTION - A\xe7\xe3o Social': 1,
        'ACTION - Bares': 17,
        'ACTION - Empresa': 63,
        'ACTION - Escola': 108,
        'ACTION - Eventos': 75,
        'ACTION - Fiscaliza\xe7\xe3o': 0,
        'ACTION - Geral': 502,
        'ACTION - Outros': 366,
        'ACTION - Ped\xe1gio': 2,
        'ACTION - Pontos tur\xedsticos': 0,
        'ACTION - Praia': 24,
        'ACTION - Pra\xe7as Esportivas': 7,
        'ACTION - Pra\xe7as/Parques P\xfablicos': 0,
        'ACTION - Shopping': 10,
        'ACTION - Universidade': 0,
        'AUDIENCE - ACOES': 70534,
        'AUDIENCE - Geral': 84703,
        'AUDIENCE - PALESTRAS': 14169,
        'LECTURES - Geral': 171,
        'MATERIAL - Certificados': 0,
        'MATERIAL - Geral': 52820,
        'MATERIAL - Soprinho': 13786,
    },
}
