# Generated by Django 5.0.7 on 2026-05-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='action_type',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='agenda',
            name='activity_type',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='agenda',
            name='address',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='agenda',
            name='agents',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='agenda',
            name='audience',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='agenda',
            name='chief_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='agenda',
            name='city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='agenda',
            name='external_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='agenda',
            name='external_responsible',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='agenda',
            name='external_responsible_phone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='agenda',
            name='institution_location',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='agenda',
            name='kit_1',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='agenda',
            name='kit_1_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agenda',
            name='kit_2',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='agenda',
            name='kit_2_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agenda',
            name='kit_3',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='agenda',
            name='kit_3_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agenda',
            name='kit_4',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='agenda',
            name='kit_4_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agenda',
            name='kit_5',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='agenda',
            name='kit_5_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agenda',
            name='kit_6',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='agenda',
            name='kit_6_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agenda',
            name='kit_7',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='agenda',
            name='kit_7_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agenda',
            name='material_1',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='agenda',
            name='material_2',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='agenda',
            name='material_3',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='agenda',
            name='material_4',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='agenda',
            name='material_5',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='agenda',
            name='material_6',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='agenda',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='agenda',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agenda',
            name='schedule_text',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='agenda',
            name='support_1',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='agenda',
            name='support_2',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='agenda',
            name='team_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='agenda',
            name='team_phone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='agenda',
            name='vehicle',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
