# Generated by Django 5.0.7 on 2026-05-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_actiontype_agent_chief_kit_material_municipality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actiontype',
            name='source_id',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='external_responsible_phone',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='source_id',
            field=models.CharField(blank=True, max_length=80, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='team_phone',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='agent',
            name='source_id',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='chief',
            name='phone',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='chief',
            name='source_id',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='kit',
            name='source_id',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='material',
            name='source_id',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='source_id',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='source_id',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='support',
            name='source_id',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='team',
            name='source_id',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='source_id',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
