# Generated by Django 5.0.7 on 2026-05-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_alter_actiontype_source_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('APPROVED', 'Aprovada'), ('CANCELLED', 'Cancelada'), ('COMPLETED', 'Concluída')], default='PENDING', max_length=20),
        ),
    ]
