# Generated by Django 5.0.7 on 2026-05-28 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0005_alter_agenda_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('SUBMITTED', 'Enviado')], default='DRAFT', max_length=20)),
                ('objective_status', models.CharField(choices=[('FULL', 'Totalmente atingido'), ('PARTIAL', 'Parcialmente atingido'), ('NOT_REACHED', 'Não atingido')], default='FULL', max_length=20)),
                ('participants_count', models.PositiveIntegerField(blank=True, null=True)),
                ('audience_profile', models.CharField(blank=True, max_length=220)),
                ('execution_summary', models.TextField()),
                ('public_receptivity', models.TextField(blank=True)),
                ('incidents', models.TextField(blank=True)),
                ('materials_used', models.TextField(blank=True)),
                ('team_performance', models.TextField(blank=True)),
                ('positive_points', models.TextField(blank=True)),
                ('improvement_points', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('final_considerations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('agenda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event_report', to='schedules.agenda')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
