# Generated by Django 5.0.7 on 2026-05-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0006_eventreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventreport',
            name='execution_quality',
            field=models.CharField(choices=[('AS_PLANNED', 'Executada conforme planejado'), ('PARTIAL_CHANGE', 'Executada com ajustes'), ('NOT_EXECUTED', 'Não executada')], default='AS_PLANNED', max_length=20),
        ),
        migrations.AddField(
            model_name='eventreport',
            name='incident_status',
            field=models.CharField(choices=[('NONE', 'Sem ocorrências'), ('MINOR', 'Ocorrências sem impacto'), ('RELEVANT', 'Ocorrências relevantes')], default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='eventreport',
            name='material_status',
            field=models.CharField(choices=[('ADEQUATE', 'Materiais suficientes'), ('PARTIAL', 'Materiais parcialmente suficientes'), ('INSUFFICIENT', 'Materiais insuficientes')], default='ADEQUATE', max_length=20),
        ),
        migrations.AddField(
            model_name='eventreport',
            name='receptivity_level',
            field=models.CharField(choices=[('HIGH', 'Alta receptividade'), ('MEDIUM', 'Receptividade moderada'), ('LOW', 'Baixa receptividade')], default='HIGH', max_length=20),
        ),
        migrations.AddField(
            model_name='eventreport',
            name='team_performance_status',
            field=models.CharField(choices=[('EXCELLENT', 'Excelente'), ('ADEQUATE', 'Adequada'), ('NEEDS_SUPPORT', 'Necessita apoio')], default='ADEQUATE', max_length=20),
        ),
    ]
