# Generated by Django 5.1.4 on 2026-05-29 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0013_agenda_linked_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('LOCAL', 'Local'), ('HORUS', 'Horus')], default='LOCAL', max_length=20)),
                ('source_id', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('operation_date', models.DateField()),
                ('team', models.CharField(max_length=160)),
                ('management_id', models.IntegerField(blank=True, null=True)),
                ('management_name', models.CharField(blank=True, max_length=180)),
                ('education_pcd', models.TextField(blank=True)),
                ('education_agents', models.TextField(blank=True)),
                ('changes_staff', models.TextField(blank=True)),
                ('breathalyzers', models.CharField(blank=True, max_length=220)),
                ('cars', models.CharField(blank=True, max_length=220)),
                ('changes_general', models.TextField(blank=True)),
                ('contact_received', models.CharField(blank=True, max_length=220)),
                ('occurrence_observation', models.TextField(blank=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('SUBMITTED', 'Enviado')], default='DRAFT', max_length=20)),
                ('horus_created_at', models.DateTimeField(blank=True, null=True)),
                ('horus_updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='education_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-operation_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EducationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('place_action', models.CharField(blank=True, max_length=260)),
                ('type_action', models.CharField(blank=True, max_length=160)),
                ('type_audience', models.CharField(blank=True, max_length=160)),
                ('institution_name', models.CharField(blank=True, max_length=220)),
                ('start_time', models.CharField(blank=True, max_length=30)),
                ('final_hour', models.CharField(blank=True, max_length=30)),
                ('approach', models.PositiveIntegerField(default=0)),
                ('tests', models.PositiveIntegerField(default=0)),
                ('used_caps', models.PositiveIntegerField(default=0)),
                ('available_caps', models.PositiveIntegerField(default=0)),
                ('distributed_folders', models.PositiveIntegerField(default=0)),
                ('cricris', models.PositiveIntegerField(default=0)),
                ('vetarolas', models.PositiveIntegerField(default=0)),
                ('used_adhesives', models.PositiveIntegerField(default=0)),
                ('sequence_certificates', models.PositiveIntegerField(default=0)),
                ('gibis', models.PositiveIntegerField(default=0)),
                ('distributed_certificates', models.PositiveIntegerField(default=0)),
                ('horus_created_at', models.DateTimeField(blank=True, null=True)),
                ('horus_updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agenda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='education_actions', to='schedules.agenda')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='schedules.educationreport')),
            ],
            options={
                'ordering': ['start_time', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='educationreport',
            index=models.Index(fields=['operation_date', 'team'], name='schedules_e_operati_ef1cb6_idx'),
        ),
        migrations.AddIndex(
            model_name='educationreport',
            index=models.Index(fields=['source', 'operation_date'], name='schedules_e_source_aca03a_idx'),
        ),
    ]
