# Generated by Django 5.1.4 on 2026-05-29 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0014_educationreport_educationaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationreport',
            name='agenda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='technical_reports', to='schedules.agenda'),
        ),
    ]
