# Generated by Django 5.1.4 on 2026-05-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0015_educationreport_agenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationreport',
            name='source',
            field=models.CharField(choices=[('LOCAL', 'Local'), ('IMPORTED', 'Importado')], default='LOCAL', max_length=20),
        ),
    ]
