# Generated by Django 5.1.4 on 2026-05-29 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0016_alter_educationreport_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='address',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='agent',
            name='role',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='chief',
            name='address',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='chief',
            name='role',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='chief',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chiefs', to='schedules.team'),
        ),
    ]
