# Generated by Codex on 2026-05-29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0017_agent_address_agent_role_chief_address_chief_role_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="support",
            name="address",
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name="support",
            name="role",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="support",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supports",
                to="schedules.team",
            ),
        ),
    ]
