# Generated by Django 5.1.4 on 2026-06-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0018_support_team_role_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationaction',
            name='approached_actions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='educationaction',
            name='approached_lectures',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='educationaction',
            name='bars',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='educationaction',
            name='beach',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='educationaction',
            name='companies',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='educationaction',
            name='educational_actions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='educationaction',
            name='events',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='educationaction',
            name='lectures',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='educationaction',
            name='other_actions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='educationaction',
            name='publicity_materials',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='educationaction',
            name='schools',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='educationaction',
            name='shopping',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='educationaction',
            name='social_actions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='educationaction',
            name='sports',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='educationaction',
            name='tolls',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='educationaction',
            name='universities',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
