# Generated by Django 5.1.4 on 2026-06-01 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0021_seed_education_goals_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='SatisfactionSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=180, unique=True)),
                ('requester_email', models.EmailField(blank=True, max_length=254)),
                ('team', models.CharField(blank=True, max_length=160)),
                ('chief_name', models.CharField(blank=True, max_length=160)),
                ('audiovisual_resources', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('speaker_knowledge', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('wheelchair_testimony', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('workshops', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('support_material', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('punctuality', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('team_enthusiasm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('overall_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('suggestion', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='satisfaction_surveys', to='schedules.agenda')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='satisfaction_surveys', to='schedules.educationreport')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
