# Generated by Django 5.0.7 on 2026-06-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0028_shiftswaprequest_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftschedule',
            name='extra_agents',
            field=models.ManyToManyField(blank=True, related_name='extra_shift_schedules', to='schedules.agent'),
        ),
        migrations.AddField(
            model_name='shiftschedule',
            name='extra_chiefs',
            field=models.ManyToManyField(blank=True, related_name='extra_shift_schedules', to='schedules.chief'),
        ),
        migrations.AddField(
            model_name='shiftschedule',
            name='extra_supports',
            field=models.ManyToManyField(blank=True, related_name='extra_shift_schedules', to='schedules.support'),
        ),
        migrations.AddField(
            model_name='shiftschedule',
            name='removed_agents',
            field=models.ManyToManyField(blank=True, related_name='removed_shift_schedules', to='schedules.agent'),
        ),
        migrations.AddField(
            model_name='shiftschedule',
            name='removed_chiefs',
            field=models.ManyToManyField(blank=True, related_name='removed_shift_schedules', to='schedules.chief'),
        ),
        migrations.AddField(
            model_name='shiftschedule',
            name='removed_supports',
            field=models.ManyToManyField(blank=True, related_name='removed_shift_schedules', to='schedules.support'),
        ),
    ]
