# Generated by Django 5.0.7 on 2026-06-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0029_shiftschedule_extra_agents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftschedule',
            name='absent_agents',
            field=models.ManyToManyField(blank=True, related_name='absent_shift_schedules', to='schedules.agent'),
        ),
        migrations.AddField(
            model_name='shiftschedule',
            name='absent_chiefs',
            field=models.ManyToManyField(blank=True, related_name='absent_shift_schedules', to='schedules.chief'),
        ),
        migrations.AddField(
            model_name='shiftschedule',
            name='absent_supports',
            field=models.ManyToManyField(blank=True, related_name='absent_shift_schedules', to='schedules.support'),
        ),
    ]
