# Generated by Codex on 2026-06-12

from django.db import migrations, models


def populate_service_order_numbers(apps, schema_editor):
    Agenda = apps.get_model("schedules", "Agenda")
    realized_statuses = ["APPROVED", "COMPLETED"]
    for number, agenda in enumerate(Agenda.objects.filter(status__in=realized_statuses).order_by("id"), start=1):
        agenda.service_order_number = number
        agenda.save(update_fields=["service_order_number"])


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0030_shiftschedule_absent_agents_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agenda",
            name="service_order_number",
            field=models.PositiveIntegerField(blank=True, db_index=True, editable=False, null=True, unique=True),
        ),
        migrations.RunPython(populate_service_order_numbers, migrations.RunPython.noop),
    ]
