# Generated by Codex on 2026-06-12

from django.db import migrations, models


def make_service_order_nullable(apps, schema_editor):
    Agenda = apps.get_model("schedules", "Agenda")
    old_field = Agenda._meta.get_field("service_order_number").clone()
    new_field = Agenda._meta.get_field("service_order_number").clone()
    for field in [old_field, new_field]:
        field.model = Agenda
        field.set_attributes_from_name("service_order_number")
        field.concrete = True
    old_field.null = False
    old_field.blank = False
    new_field.null = True
    new_field.blank = True
    schema_editor.alter_field(Agenda, old_field, new_field, strict=False)


def renumber_realized_service_orders(apps, schema_editor):
    Agenda = apps.get_model("schedules", "Agenda")
    realized_statuses = ["APPROVED", "COMPLETED"]
    Agenda.objects.exclude(status__in=realized_statuses).update(service_order_number=None)
    for number, agenda in enumerate(Agenda.objects.filter(status__in=realized_statuses).order_by("id"), start=1):
        agenda.service_order_number = number
        agenda.save(update_fields=["service_order_number"])


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0031_agenda_service_order_number"),
    ]

    operations = [
        migrations.RunPython(make_service_order_nullable, migrations.RunPython.noop),
        migrations.RunPython(renumber_realized_service_orders, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="agenda",
            name="service_order_number",
            field=models.PositiveIntegerField(blank=True, db_index=True, editable=False, null=True, unique=True),
        ),
    ]
