# Generated by Django 5.0.7 on 2026-06-18 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0036_educationreport_accessibility_conditions_met_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_type', models.CharField(choices=[('CHIEF', 'Chefe'), ('AGENT', 'Agente'), ('SUPPORT', 'Apoio')], max_length=16)),
                ('member_id', models.PositiveIntegerField()),
                ('member_name', models.CharField(max_length=180)),
                ('reason', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='shift_absences/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_shift_absences', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absence_records', to='schedules.shiftschedule')),
            ],
            options={
                'ordering': ['member_name'],
                'indexes': [models.Index(fields=['schedule', 'member_type'], name='shift_abs_sched_type_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='shiftabsence',
            constraint=models.UniqueConstraint(fields=('schedule', 'member_type', 'member_id'), name='unique_shift_absence_member'),
        ),
    ]
