# Generated by Codex on 2026-06-23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0041_accessibilityblocklist_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='accessibility_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_agendas', to='schedules.accessibilityblocklist'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='accessibility_rejection_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agenda',
            name='accessibility_rejection_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='agenda',
            index=models.Index(fields=['accessibility_rejection_due_at', 'accessibility_rejection_sent_at'], name='schedules_a_access_9d6988_idx'),
        ),
    ]
