# Generated by Django 5.1.4 on 2026-06-23 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0044_dynamic_alter_kit_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamaterial',
            name='dynamic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedules.dynamic'),
        ),
    ]
