# Generated by Django 5.1.4 on 2026-06-26 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0045_agendamaterial_dynamic'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamic',
            name='materials',
            field=models.TextField(blank=True, default=''),
        ),
    ]
