# Generated by Django 5.1.4 on 2026-07-01 19:57

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0050_satisfactionsurvey_survey_status_answered_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        TrigramExtension(),
        migrations.AlterModelOptions(
            name='agenda',
            options={},
        ),
        migrations.AddIndex(
            model_name='agenda',
            index=django.contrib.postgres.indexes.GinIndex(fields=['action_type'], name='action_type_gin_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
