# Generated by Django 5.1.4 on 2026-07-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0052_userteamtransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftschedule',
            name='attendance_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shiftschedule',
            name='attendance_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shiftschedule',
            name='attendance_reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shiftschedule',
            name='attendance_reported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
