# Generated by Django 5.1.4 on 2026-07-09 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0053_shiftschedule_attendance_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actiontype',
            name='vacation_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actiontype',
            name='vacation_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='vacation_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='vacation_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chief',
            name='vacation_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chief',
            name='vacation_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dynamic',
            name='vacation_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dynamic',
            name='vacation_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kit',
            name='vacation_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kit',
            name='vacation_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='vacation_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='vacation_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='municipality',
            name='vacation_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='municipality',
            name='vacation_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='vacation_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='vacation_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='vacation_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='vacation_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='support',
            name='vacation_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='support',
            name='vacation_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='vacation_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='vacation_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vacation_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vacation_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
