# Generated by Django 5.1.4 on 2026-07-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0054_actiontype_vacation_end_actiontype_vacation_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationreport',
            name='no_photo_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='educationreport',
            name='photo_1',
            field=models.FileField(blank=True, null=True, upload_to='education_reports/'),
        ),
        migrations.AddField(
            model_name='educationreport',
            name='photo_2',
            field=models.FileField(blank=True, null=True, upload_to='education_reports/'),
        ),
    ]
