# Generated by Django 5.1.4 on 2026-07-14 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0062_shiftschedule_checked_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationreport',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Rascunho'), ('PENDING_REVIEW', 'Aguardando conferência'), ('APPROVED', 'Aprovado'), ('RETURNED', 'Devolvido para correção'), ('SUBMITTED', 'Enviado')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='reportstatushistory',
            name='new_status',
            field=models.CharField(choices=[('DRAFT', 'Rascunho'), ('PENDING_REVIEW', 'Aguardando conferência'), ('APPROVED', 'Aprovado'), ('RETURNED', 'Devolvido para correção'), ('SUBMITTED', 'Enviado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reportstatushistory',
            name='old_status',
            field=models.CharField(blank=True, choices=[('DRAFT', 'Rascunho'), ('PENDING_REVIEW', 'Aguardando conferência'), ('APPROVED', 'Aprovado'), ('RETURNED', 'Devolvido para correção'), ('SUBMITTED', 'Enviado')], max_length=20, null=True),
        ),
    ]
