# Generated by Django 5.1.4 on 2026-07-17 15:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0064_educationaction_joint_inspections'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='designated_users',
            field=models.ManyToManyField(blank=True, related_name='designated_service_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agenda',
            name='service_order_mode',
            field=models.CharField(choices=[('TEAM', 'Equipe operacional'), ('DESIGNATED', 'Participantes selecionados')], db_index=True, default='TEAM', max_length=20),
        ),
    ]
