# Generated by Django 5.0.3 on 2026-07-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0065_agenda_designated_users_agenda_service_order_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationaction',
            name='parks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='educationaction',
            name='tourist_spots',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
