# Generated by Django 6.0.4 on 2026-07-23 12:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0066_educationreport_parks_educationreport_tourist_spots'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='absent_designated_users',
            field=models.ManyToManyField(blank=True, related_name='absent_designated_service_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
