# Generated by Django 6.0.4 on 2026-07-23 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0067_agenda_absent_designated_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='educationreport',
            name='statistics_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='educationreport',
            name='statistics_processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationreport',
            name='statistics_processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_statistics_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
