# Generated by Django 5.1.4 on 2026-08-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0071_agenda_administrative_demand_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationreport',
            name='exceptional_occurrence_actions_taken',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='educationreport',
            name='exceptional_occurrence_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='educationreport',
            name='exceptional_occurrence_impact',
            field=models.CharField(blank=True, choices=[('NO_IMPACT', 'Sem preju\u00edzo'), ('PARTIAL', 'Prejudicada parcialmente'), ('INTERRUPTED', 'Interrompida')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='educationreport',
            name='exceptional_occurrence_type',
            field=models.CharField(blank=True, choices=[('VEHICLE_BREAKDOWN', 'Quebra ou pane de viatura'), ('WORK_ACCIDENT', 'Acidente de trabalho'), ('MEDICAL_ASSISTANCE', 'Atendimento m\u00e9dico'), ('EQUIPMENT_OR_MATERIAL', 'Problema com equipamento ou material'), ('ACTIVITY_INTERRUPTION', 'Interrup\u00e7\u00e3o da atividade'), ('SECURITY_INCIDENT', 'Ocorr\u00eancia de seguran\u00e7a'), ('SEVERE_WEATHER', 'Condi\u00e7\u00e3o clim\u00e1tica grave'), ('OTHER', 'Outro')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='educationreport',
            name='has_exceptional_occurrence',
            field=models.BooleanField(default=False),
        ),
    ]

