# Generated by Django 5.1.4 on 2026-08-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0072_educationreport_exceptional_occurrence_actions_taken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='travel_displacement',
            field=models.BooleanField(default=False, verbose_name='Deslocamento de viagem'),
        ),
    ]
