# Generated by Django 5.1.4 on 2026-08-06 14:57

from django.db import migrations


def migrate_travel_displacement(apps, schema_editor):
    Agenda = apps.get_model('schedules', 'Agenda')
    Agenda.objects.filter(
        administrative_demand_type="TRAVEL"
    ).update(
        travel_displacement=True
    )

class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0073_agenda_travel_displacement'),
    ]

    operations = [
        migrations.RunPython(migrate_travel_displacement, reverse_code=migrations.RunPython.noop),
    ]
