# Generated by Django 5.1.4 on 2026-08-21 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0075_externalrequestdateblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='actiontype',
            name='category',
            field=models.CharField(blank=True, choices=[('STREET_ACTION', 'Ação de Rua'), ('LECTURE', 'Palestra'), ('EDUCATIONAL_ACTION', 'Ação Educativa'), ('PROGRAM_INDICATOR', 'Indicador de Programa'), ('OTHER', 'Outros')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='educationaction',
            name='age_range',
            field=models.CharField(blank=True, choices=[('AGE_05_10', '05 - 10 anos (ensino fundamental - anos iniciais)'), ('AGE_11_14', '11 - 14 anos (ensino fundamental - anos finais)'), ('AGE_15_17', '15 - 17 anos (ensino médio)'), ('AGE_ADULT', 'acima de 18 anos - Adultos')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='educationaction',
            name='agreement_indicator',
            field=models.CharField(blank=True, choices=[('ESCOLINHA_NOTA_10', 'Escolinha Nota 10'), ('ESCOLA_NOTA_10', 'Escola Nota 10')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='educationaction',
            name='requester_entity_kind',
            field=models.CharField(blank=True, choices=[('SCHOOL', 'Instituição de Ensino'), ('BUSINESS', 'Empresa'), ('MILITARY', 'Órgão Militar'), ('PUBLIC', 'Órgão Público'), ('OTHER', 'Outros')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='educationaction',
            name='requester_entity_nature',
            field=models.CharField(blank=True, choices=[('PUBLIC', 'Pública'), ('PRIVATE', 'Privada')], max_length=50, null=True),
        ),
    ]
