# Generated by Django 5.1.4 on 2026-06-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_is_on_vacation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vacation_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='vacation_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
