# Generated by Django 5.1.4 on 2026-07-09 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_user_vacation_end_user_vacation_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('MANAGER', 'Gestor'), ('SUPERVISOR', 'Supervisor'), ('VISITOR', 'Visitante'), ('USER', 'Usuário comum'), ('SUPPORT', 'Apoio'), ('ALMOXARIFADO', 'Almoxarifado')], default='USER', max_length=20),
        ),
    ]
