# Generated by Django 5.1.4 on 2026-07-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lgpd_consent_at',
            field=models.DateTimeField(blank=True, help_text='Data e hora em que o usuário aceitou a política de privacidade.', null=True, verbose_name='Data de aceite LGPD'),
        ),
    ]
