import { useEffect, useMemo, useRef, useState } from "react";
import { Activity, AlertTriangle, ArrowRight, BarChart3, BookOpen, Building2, CalendarDays, Download, FileImage, FileSpreadsheet, Filter, Lightbulb, MapPin, Printer, TrendingDown, TrendingUp, Users, X } from "lucide-react";
import { Bar, CartesianGrid, ComposedChart, LabelList, Legend, Line, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { toPng } from "html-to-image";
import { api } from "../api/client.js";
import { formatLocalISODate } from "../utils/date.js";
import "./StatisticsPage.css";

const MIN_DATE = "2026-07-01";
const COLORS = ["#0048d7", "#059669", "#dc2626", "#7c3aed", "#ea580c", "#db2777", "#0891b2", "#ca8a04", "#64748b", "#16a34a"];
const number = (value) => Number(value || 0).toLocaleString("pt-BR", { maximumFractionDigits: 1 });
const integer = (value) => Number(value || 0).toLocaleString("pt-BR", { maximumFractionDigits: 0 });
const iso = (value) => value instanceof Date ? formatLocalISODate(value) : value;
const clampStart = (value) => !value || value < MIN_DATE ? MIN_DATE : value;
const queryString = (values) => new URLSearchParams(Object.entries(values).filter(([, value]) => value !== "" && value != null)).toString();
const text = {
  publicReached: "P\u00fablico alcan\u00e7ado", futurePublic: "P\u00fablico previsto das pr\u00f3ximas agendas", reportsApproved: "Realizado nos relat\u00f3rios aprovados",
  futureHint: "Solicita\u00e7\u00f5es externas aprovadas e futuras", lectures: "Palestras", street: "A\u00e7\u00f5es de rua", materials: "Materiais distribu\u00eddos",
  comics: "Revistinhas distribu\u00eddas", internal: "Solicita\u00e7\u00f5es internas", public: "Solicita\u00e7\u00f5es p\u00fablicas", internalHint: "Agendas criadas pela equipe",
  publicHint: "Solicita\u00e7\u00f5es recebidas pelo formul\u00e1rio", noData: "Sem dados para os filtros selecionados.", notInformed: "N\u00e3o informado",
};
const KPI_DEFS = [
  ["AUDIENCE - Geral", text.publicReached, Users, COLORS[0], text.reportsApproved],
  ["FUTURE_PUBLIC", text.futurePublic, Users, COLORS[1], text.futureHint],
  ["LECTURES - Geral", text.lectures, BarChart3, COLORS[3], "Relat\u00f3rios aprovados de palestras"],
  ["STREET_ACTIONS - Geral", text.street, Activity, COLORS[4], "Relat\u00f3rios aprovados de a\u00e7\u00f5es de rua"],
  ["MATERIAL - Geral", text.materials, BookOpen, COLORS[5], "Total entregue"],
  ["MATERIAL - Soprinho", text.comics, BookOpen, COLORS[7], "Soprinho"],
  ["INTERNAL_REQUESTS", text.internal, Building2, COLORS[0], text.internalHint],
  ["PUBLIC_REQUESTS", text.public, Users, COLORS[1], text.publicHint],
];
const HISTORICAL_ROWS = [
  ["AUDIENCE - Geral", "1 - P\u00fablico total"], ["AUDIENCE - PALESTRAS", "1.1 - P\u00fablico em palestras"], ["AUDIENCE - ACOES", "1.2 - P\u00fablico em a\u00e7\u00f5es"],
  ["LECTURES - Geral", "2 - Palestras realizadas"], ["ACTION - Escola", "2.1 - Escolas"], ["ACTION - Universidade", "2.2 - Universidades"], ["ACTION - Empresa", "2.3 - Empresas"],
  ["STREET_ACTIONS - Geral", "3 - A\u00e7\u00f5es de rua"], ["ACTION - Bares", "3.1 - Bares"], ["ACTION - Ped\u00e1gio", "3.2 - Ped\u00e1gio"], ["ACTION - Pra\u00e7as Esportivas", "3.3 - Esportes"],
  ["ACTION - Praia", "3.4 - Praia"], ["ACTION - Eventos", "3.5 - Eventos"], ["ACTION - Shopping", "3.6 - Shopping/Centro Comercial"], ["ACTION - A\u00e7\u00e3o Social", "3.7 - A\u00e7\u00e3o Social"],
  ["ACTION - Outros", "3.8 - Outros"], ["ACTION - Pra\u00e7as/Parques P\u00fablicos", "3.9 - Pra\u00e7as/Parques P\u00fablicos"], ["ACTION - Pontos tur\u00edsticos", "3.10 - Pontos tur\u00edsticos"],
  ["ACTION - A\u00e7\u00e3o conjunta com a fiscaliza\u00e7\u00e3o", "3.11 - A\u00e7\u00e3o conjunta com a fiscaliza\u00e7\u00e3o"], ["MATERIAL - Geral", "4 - Materiais de divulga\u00e7\u00e3o"], ["MATERIAL - Soprinho", "Revistinha Soprinho"],
];
function Empty({ children = text.noData }) { return <div className="stats-empty">{children}</div>; }
function Section({ icon: Icon, title, subtitle, children, actions, className = "" }) { return <section className={`stats-panel ${className}`}><header className="stats-panel-header"><div className="stats-panel-title"><span className="stats-icon"><Icon size={17}/></span><div><h2>{title}</h2>{subtitle && <p>{subtitle}</p>}</div></div>{actions && <div className="stats-panel-actions">{actions}</div>}</header><div className="stats-panel-body">{children}</div></section>; }
function MetricCard({ definition, summary, previous, comparison }) { const [key, label, Icon, color, hint] = definition; const value = Number(summary?.[key] || 0); const prior = Number(previous?.[key] || 0); const pct = comparison?.[key]?.percentage; const Trend = pct < 0 ? TrendingDown : TrendingUp; return <article className="stats-kpi" style={{ "--kpi": color }}><div className="stats-kpi-top"><span className="stats-kpi-icon"><Icon size={18}/></span><span>{label}</span></div><div className="stats-kpi-value">{number(value)}</div><div className={`stats-kpi-delta ${pct < 0 ? "is-down" : "is-up"}`}><Trend size={14}/>{pct == null ? (value ? "Novo" : "0,0%") : `${pct >= 0 ? "+" : ""}${pct.toFixed(1)}%`} <span>vs. {number(prior)}</span></div>{hint && <small>{hint}</small>}</article>; }
function MiniCard({ label, value, hint, icon: Icon = BarChart3, tone = COLORS[0] }) { return <div className="stats-mini-card"><span style={{ background: tone }}><Icon size={15}/></span><strong>{number(value)}</strong><small>{label}</small>{hint && <em>{hint}</em>}</div>; }
function ExecutiveBar({ rows, maxRows = 12 }) { const visible = (rows || []).filter(row => Number(row.actions || 0) > 0 || Number(row.audience || 0) > 0).slice(0, maxRows); if (!visible.length) return <Empty/>; const total = visible.reduce((sum, row) => sum + Number(row.actions || 0), 0) || 1; const max = Math.max(...visible.map(row => Number(row.actions || 0)), 1); return <div className="stats-exec-bars">{visible.map((row, index) => { const pct = Number(row.actions || 0) / total * 100; return <button key={`${row.label}-${index}`} onClick={row.onClick} className="stats-exec-bar"><span className="stats-exec-label"><b>{row.label}</b><small>{integer(row.actions)} a\u00e7\u00f5es \u2022 {integer(row.audience)} pessoas \u2022 {pct.toFixed(1)}%</small></span><i><em style={{ width: `${Math.max(3, Number(row.actions || 0) / max * 100)}%`, background: row.color || COLORS[index % COLORS.length] }}/></i></button>; })}</div>; }
function RankingTabs({ tabs }) { const [active, setActive] = useState(tabs[0]?.key); const tab = tabs.find(item => item.key === active) || tabs[0]; return <div><div className="stats-tabs">{tabs.map(item => <button key={item.key} className={item.key === active ? "active" : ""} onClick={() => setActive(item.key)}>{item.label}</button>)}</div><Ranking rows={tab.rows} nameKey={tab.nameKey}/></div>; }
function Ranking({ rows, nameKey }) { const visible = (rows || []).filter(row => Number(row.actions || 0) > 0 || Number(row.audience || 0) > 0); if (!visible.length) return <Empty/>; const max = Math.max(...visible.map(row => Number(row.actions || 0)), 1); return <div className="stats-ranking">{visible.map((row, index) => <div className="stats-rank-row" key={`${row[nameKey]}-${index}`}><b>{index + 1}</b><span>{row[nameKey] || text.notInformed}</span><div><i style={{ width: `${Number(row.actions || 0) / max * 100}%` }}/></div><strong>{number(row.actions)}</strong><small>{number(row.audience)} p\u00fablico</small></div>)}</div>; }
const parseExpected = (...values) => { for (const value of values) { const raw = String(value ?? "").trim(); if (!raw) continue; const nums = raw.match(/\d+/g)?.map(Number); if (nums?.length) return Math.max(...nums); } return 0; };
const cleanLabel = (value) => String(value || "").trim() || text.notInformed;
const groupBy = (items, getLabel) => Object.values(items.reduce((acc, item) => { const label = cleanLabel(getLabel(item)); acc[label] ||= { label, actions: 0, audience: 0 }; acc[label].actions += 1; acc[label].audience += parseExpected(item.audience, item.participant_range, item.quantity); return acc; }, {})).sort((a,b) => b.actions - a.actions);
export default function StatisticsPage() {
  const now = new Date(); const dashboardRef = useRef(null); const defaultFilters = { date_from: MIN_DATE, date_to: iso(now), municipality: "", team: "", action_type: "", entity: "", institution: "" };
  const [filters, setFilters] = useState(defaultFilters); const [pending, setPending] = useState(defaultFilters); const [options, setOptions] = useState({ municipalities: [], teams: [], action_types: [], entities: [], institutions: [] }); const [data, setData] = useState(null); const [agendas, setAgendas] = useState([]); const [futureAgendas, setFutureAgendas] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [drilldown, setDrilldown] = useState(null);
  useEffect(() => { api("/statistics/dashboard/filters/").then(setOptions).catch(() => {}); }, []);
  useEffect(() => { const safeFilters = { ...filters, date_from: clampStart(filters.date_from) }; setLoading(true); setError(""); Promise.all([api(`/statistics/dashboard/?${queryString(safeFilters)}`), api(`/agendas/?date_from=${safeFilters.date_from}&date_to=${safeFilters.date_to}&page_size=500`), api(`/agendas/?date_from=${iso(now)}&date_to=2100-12-31&status=APPROVED&page_size=500`)]).then(([stats, agendaResult, futureResult]) => { setData(stats); setAgendas(agendaResult.results || agendaResult || []); setFutureAgendas(futureResult.results || futureResult || []); }).catch(err => setError(err.message)).finally(() => setLoading(false)); }, [filters]);
  const annual = useMemo(() => (data?.annual || []).map(row => ({ year: row.year, ...row.values })), [data]); const dailySeries = useMemo(() => (data?.daily || []).map(row => ({ day: row.day_label || row.date, actions: Number(row.values["ACTION - Geral"] || 0), audience: Number(row.values["AUDIENCE - Geral"] || 0) })), [data]); const categoryData = useMemo(() => (data?.categories || []).map((row, index) => ({ ...row, value: Number(row.value || 0), actions: Number(row.value || 0), audience: Number(row.audience || 0), color: COLORS[index % COLORS.length] })).sort((a,b) => b.value - a.value), [data]);
  const totalActions = Number(data?.summary?.["ACTION - Geral"] || 0); const demand = useMemo(() => { const total = agendas.length; const publicForm = agendas.filter(a => a.origin === "PUBLIC_FORM").length; const internal = agendas.filter(a => a.origin === "INTERNAL").length; const approved = agendas.filter(a => ["APPROVED", "COMPLETED"].includes(a.status)).length; const cancelled = agendas.filter(a => a.status === "CANCELLED").length; const refused = agendas.filter(a => ["REJECTED", "REFUSED"].includes(a.status)).length; return { total, publicForm, internal, approved, cancelled, refused, executed: totalActions }; }, [agendas, totalActions]);
  const publicRequests = agendas.filter(a => a.origin === "PUBLIC_FORM").length; const internalRequests = agendas.filter(a => a.origin !== "PUBLIC_FORM").length; const pendingApproval = agendas.filter(a => ["PENDING", "PENDING_REVIEW"].includes(a.status)).length; const futurePublic = futureAgendas.filter(a => a.origin === "PUBLIC_FORM" && a.status === "APPROVED").reduce((sum, agenda) => sum + parseExpected(agenda.audience, agenda.participant_range), 0); const displaySummary = { ...(data?.summary || {}), FUTURE_PUBLIC: futurePublic, INTERNAL_REQUESTS: internalRequests, PUBLIC_REQUESTS: publicRequests }; const displayPrevious = { ...(data?.previous || {}), FUTURE_PUBLIC: 0, INTERNAL_REQUESTS: 0, PUBLIC_REQUESTS: 0 }; const displayComparisons = { ...(data?.comparisons || {}), FUTURE_PUBLIC: { percentage: null }, INTERNAL_REQUESTS: { percentage: null }, PUBLIC_REQUESTS: { percentage: null } };
  const ageRows = useMemo(() => groupBy(agendas, a => a.age_ranges), [agendas]); const requesterRows = useMemo(() => groupBy(agendas, a => a.requester_entity_type), [agendas]); const modalityRows = useMemo(() => groupBy(agendas, a => a.action_type), [agendas]); const municipalities = data?.municipalities || []; const teams = data?.teams || []; const bestTeam = teams[0] || {}; const topCategory = categoryData[0] || {}; const insights = [`${topCategory.label || "Categoria principal"} concentra ${totalActions ? (Number(topCategory.value || 0) / totalActions * 100).toFixed(1) : "0,0"}% das a\u00e7\u00f5es.`, `${bestTeam.team || "Equipe"} lidera em volume com ${integer(bestTeam.actions)} a\u00e7\u00f5es.`, `${integer(data?.summary?.REPORTS_WITHOUT_PUBLIC)} relat\u00f3rios aprovados est\u00e3o sem p\u00fablico informado.`];
  const reset = () => { setPending(defaultFilters); setFilters(defaultFilters); }; const apply = () => setFilters(current => ({ ...current, ...pending, date_from: clampStart(pending.date_from) })); const exportExcel = () => { const years = annual.map(row => row.year); const lines = [["Indicador", ...years], ...HISTORICAL_ROWS.map(([key, label]) => [label, ...annual.map(row => row[key] || 0)])]; const blob = new Blob(["\ufeff" + lines.map(line => line.join("\t")).join("\n")], { type: "application/vnd.ms-excel;charset=utf-8" }); const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = "estatisticas-sied.xls"; link.click(); URL.revokeObjectURL(link.href); }; const exportCsv = async () => { const blob = await api(`/statistics/dashboard/export.csv?${queryString(filters)}`); const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = "estatisticas-sied.csv"; link.click(); URL.revokeObjectURL(link.href); }; const exportImage = async () => { const dataUrl = await toPng(dashboardRef.current, { cacheBust: true, pixelRatio: 1.5, backgroundColor: "#f4f7fb" }); const link = document.createElement("a"); link.href = dataUrl; link.download = "dashboard-estatisticas-sied.png"; link.click(); };
  if (loading) return <section className="stats-dashboard"><div className="stats-loading">Carregando painel executivo...</div></section>; if (error) return <section className="stats-dashboard"><div className="alert">N\u00e3o foi poss\u00edvel carregar o dashboard: {error}</div></section>;
  return <section className="stats-dashboard" ref={dashboardRef}><header className="stats-hero"><div><span>{"Intelig\u00eancia institucional"}</span><h1>Dashboard Executivo SIED</h1><p>{"Indicadores oficiais a partir de 01/07/2026, quando o sistema passou a operar."}</p></div><div className="stats-export"><button onClick={() => window.print()}><Printer size={16}/>PDF</button><button onClick={exportExcel}><FileSpreadsheet size={16}/>Excel</button><button onClick={exportCsv}><Download size={16}/>CSV</button><button onClick={exportImage}><FileImage size={16}/>Imagem</button></div></header>
    <div className="stats-filters"><div className="stats-filter-title"><Filter size={17}/>{"Filtros globais"}</div><label>De<input min={MIN_DATE} type="date" value={pending.date_from} onChange={e => setPending(v => ({ ...v, date_from: clampStart(e.target.value) }))}/></label><label>{"At\u00e9"}<input min={MIN_DATE} type="date" value={pending.date_to} onChange={e => setPending(v => ({ ...v, date_to: e.target.value }))}/></label><label>{"Munic\u00edpio"}<select value={pending.municipality} onChange={e => setPending(v => ({ ...v, municipality: e.target.value }))}><option value="">Todos</option>{options.municipalities.map(v => <option key={v}>{v}</option>)}</select></label><label>Equipe<select value={pending.team} onChange={e => setPending(v => ({ ...v, team: e.target.value }))}><option value="">Todas</option>{options.teams.map(v => <option key={v}>{v}</option>)}</select></label><label>Categoria<select value={pending.entity} onChange={e => setPending(v => ({ ...v, entity: e.target.value }))}><option value="">Todas</option>{options.entities.map(v => <option key={v}>{v}</option>)}</select></label><div className="stats-filter-actions"><button className="primary" onClick={apply}>Aplicar</button><button onClick={reset}>Limpar</button></div></div>
    <div className="stats-kpi-grid stats-kpi-grid-compact">{KPI_DEFS.map(def => <MetricCard key={def[0]} definition={def} summary={displaySummary} previous={displayPrevious} comparison={displayComparisons}/>)}</div>
    <Section icon={ArrowRight} title={"Produ\u00e7\u00e3o x demanda"} subtitle={"Funil operacional das solicita\u00e7\u00f5es no per\u00edodo."}><div className="stats-demand-grid"><MiniCard label={"Solicita\u00e7\u00f5es recebidas"} value={demand.total} hint={`${integer(demand.publicForm)} p\u00fablicas \u2022 ${integer(demand.internal)} internas`}/><MiniCard label="Aprovadas" value={demand.approved}/><MiniCard label="Executadas" value={demand.executed}/><MiniCard label="Canceladas/recusadas" value={demand.cancelled + demand.refused} tone={COLORS[2]}/><MiniCard label={"A\u00e7\u00f5es com relat\u00f3rio aprovado"} value={totalActions} hint={"Relat\u00f3rios aprovados"} tone={COLORS[3]}/><MiniCard label={"Aguardando aprova\u00e7\u00e3o"} value={pendingApproval} hint={"Solicita\u00e7\u00f5es pendentes"} tone={COLORS[8]}/></div></Section>
    <Section icon={TrendingUp} title={"Evolu\u00e7\u00e3o di\u00e1ria"} subtitle={"A\u00e7\u00f5es e p\u00fablico por dia desde 01/07/2026."}><div className="stats-chart-xl"><ResponsiveContainer><ComposedChart data={dailySeries}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="day"/><YAxis yAxisId="left"/><YAxis yAxisId="right" orientation="right"/><Tooltip formatter={number}/><Legend/><Bar yAxisId="left" dataKey="actions" name={"A\u00e7\u00f5es"} fill={COLORS[0]} radius={[6,6,0,0]}><LabelList dataKey="actions" position="top" formatter={(value) => value ? integer(value) : ""}/></Bar><Line yAxisId="right" type="monotone" dataKey="audience" name={"P\u00fablico"} stroke={COLORS[4]} strokeWidth={3}><LabelList dataKey="audience" position="top" formatter={(value) => value ? integer(value) : ""}/></Line></ComposedChart></ResponsiveContainer></div></Section>
    <div className="stats-two-columns"><Section icon={BarChart3} title={"Distribui\u00e7\u00e3o por categoria"} subtitle="Somente categorias com movimento."><ExecutiveBar rows={categoryData.map(row => ({ label: row.label, actions: row.value, audience: row.audience, color: row.color, onClick: () => setDrilldown(row) }))}/></Section><Section icon={Users} title={"Faixa et\u00e1ria do p\u00fablico"} subtitle={"Perfil informado na solicita\u00e7\u00e3o."}><ExecutiveBar rows={ageRows}/></Section></div>
    <div className="stats-two-columns"><Section icon={Users} title="Perfil institucional" subtitle="Tipo de solicitante."><ExecutiveBar rows={requesterRows}/></Section><Section icon={Activity} title="Modalidade pretendida" subtitle={"Palestra, educa\u00e7\u00e3o/conscientiza\u00e7\u00e3o e a\u00e7\u00f5es de rua."}><ExecutiveBar rows={modalityRows}/></Section></div>
    <div className="stats-two-columns"><Section icon={MapPin} title={"Indicadores geogr\u00e1ficos"} subtitle={"Munic\u00edpios com produ\u00e7\u00e3o no per\u00edodo."}><Ranking rows={municipalities} nameKey="agenda__city"/></Section><Section icon={BarChart3} title="Ranking operacional" subtitle={"Categorias, equipes e munic\u00edpios."}><RankingTabs tabs={[{ key:"cat", label:"Categorias", rows: categoryData.map(row => ({ label: row.label, actions: row.value, audience: row.audience })), nameKey:"label" }, { key:"teams", label:"Equipes", rows: teams, nameKey:"team" }, { key:"mun", label:"Munic\u00edpios", rows: municipalities, nameKey:"agenda__city" }]}/></Section></div>
    <Section icon={Lightbulb} title={"Insights autom\u00e1ticos"} subtitle={"Leitura r\u00e1pida para gest\u00e3o."}><div className="stats-insights">{insights.map((insight, index) => <p key={index}>{insight}</p>)}</div></Section>
    <Section icon={BarChart3} title={"S\u00e9rie hist\u00f3rica completa"} subtitle={"Tabela institucional preservada para auditoria e exporta\u00e7\u00e3o."}><div className="stats-table-wrap"><table className="stats-table stats-history-table"><thead><tr><th>Indicador</th>{annual.map(row => <th key={row.year}>{row.year}</th>)}</tr></thead><tbody>{HISTORICAL_ROWS.map(([key, label]) => <tr key={key}><td>{label}</td>{annual.map(row => <td key={row.year}>{number(row[key])}</td>)}</tr>)}</tbody></table></div></Section>
    {drilldown && <div className="stats-drilldown"><div><button onClick={() => setDrilldown(null)}><X size={18}/></button><span>Detalhamento</span><h3>{drilldown.label}</h3><p>Total no per\u00edodo: <strong>{number(drilldown.value)}</strong></p><p>P\u00fablico: <strong>{number(drilldown.audience)}</strong></p></div></div>}
    <footer className="stats-methodology">Fonte: banco de dados SIED \u2022 demanda das agendas + produ\u00e7\u00e3o dos relat\u00f3rios aprovados.</footer></section>;
}
