# Generated by Django 5.1.4 on 2026-08-12 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.UUIDField(db_index=True, unique=True)),
                ('source_created_at', models.DateTimeField()),
                ('source_updated_at', models.DateTimeField()),
                ('synced_at', models.DateTimeField()),
                ('operation_date', models.DateField()),
                ('team', models.CharField(blank=True, max_length=120)),
                ('management_id', models.IntegerField(blank=True, null=True)),
                ('military_chief_source_id', models.UUIDField(blank=True, null=True)),
                ('segov_team_civil', models.CharField(blank=True, max_length=255)),
                ('segov_team_military', models.CharField(blank=True, max_length=255)),
                ('change_ols', models.TextField(blank=True)),
                ('agent_detran', models.IntegerField(blank=True, null=True)),
                ('number_trailers', models.IntegerField(blank=True, null=True)),
                ('change_support', models.TextField(blank=True)),
                ('cars', models.CharField(blank=True, max_length=255)),
                ('changes_general', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('SYNCED', 'Sincronizado'), ('PENDING_REVIEW', 'Aguardando revisao'), ('APPROVED', 'Aprovado'), ('RETURNED', 'Devolvido')], db_index=True, default='SYNCED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-operation_date', '-created_at'],
                'indexes': [models.Index(fields=['operation_date', 'team'], name='inspection__operati_6c7767_idx'), models.Index(fields=['status', 'operation_date'], name='inspection__status_2885b9_idx')],
            },
        ),
        migrations.CreateModel(
            name='InspectionReportOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.UUIDField(db_index=True, unique=True)),
                ('source_created_at', models.DateTimeField()),
                ('source_updated_at', models.DateTimeField()),
                ('address_operation', models.CharField(blank=True, max_length=255)),
                ('locality', models.CharField(blank=True, max_length=255)),
                ('another_not_listed', models.CharField(blank=True, max_length=255)),
                ('departure_meeting_point', models.CharField(blank=True, max_length=255)),
                ('operation_assembly', models.CharField(blank=True, max_length=255)),
                ('first_approach', models.CharField(blank=True, max_length=255)),
                ('closing', models.CharField(blank=True, max_length=255)),
                ('approach', models.IntegerField(blank=True, null=True)),
                ('reconductor', models.IntegerField(blank=True, null=True)),
                ('refusal', models.IntegerField(blank=True, null=True)),
                ('celebrities_authorities', models.IntegerField(blank=True, null=True)),
                ('four_ml', models.IntegerField(blank=True, null=True)),
                ('thirtythree_ml', models.IntegerField(blank=True, null=True)),
                ('thirtyfour_ml', models.IntegerField(blank=True, null=True)),
                ('passive_tests_performed', models.IntegerField(blank=True, null=True)),
                ('changes_material', models.TextField(blank=True)),
                ('cnh_collected', models.IntegerField(blank=True, null=True)),
                ('fined', models.IntegerField(blank=True, null=True)),
                ('towed', models.IntegerField(blank=True, null=True)),
                ('removal_resolutions', models.IntegerField(blank=True, null=True)),
                ('arrests_means_evidence', models.IntegerField(blank=True, null=True)),
                ('art307', models.IntegerField(blank=True, null=True)),
                ('criminal_occurrences', models.IntegerField(blank=True, null=True)),
                ('driving_canceled_license', models.IntegerField(blank=True, null=True)),
                ('vehicle_resolutions', models.TextField(blank=True)),
                ('administrative_tests', models.TextField(blank=True)),
                ('cep', models.CharField(blank=True, max_length=32)),
                ('street', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('district', models.CharField(blank=True, max_length=255)),
                ('number', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='inspection.inspectionreport')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='InspectionFine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.IntegerField(db_index=True, unique=True)),
                ('art', models.CharField(blank=True, max_length=120)),
                ('quant', models.IntegerField(blank=True, null=True)),
                ('source_created_at', models.DateTimeField()),
                ('source_updated_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fines', to='inspection.inspectionreportoperation')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='InspectionReportStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, choices=[('SYNCED', 'Sincronizado'), ('PENDING_REVIEW', 'Aguardando revisao'), ('APPROVED', 'Aprovado'), ('RETURNED', 'Devolvido')], max_length=20, null=True)),
                ('new_status', models.CharField(choices=[('SYNCED', 'Sincronizado'), ('PENDING_REVIEW', 'Aguardando revisao'), ('APPROVED', 'Aprovado'), ('RETURNED', 'Devolvido')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_report_status_changes', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='inspection.inspectionreport')),
            ],
            options={
                'ordering': ['changed_at'],
            },
        ),
    ]
