# Generated by Django 5.1.4 on 2026-08-12 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionStatisticsDecisionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, choices=[('PENDING', 'Aguardando analise'), ('INCLUDED', 'Incluido na estatistica'), ('EXCLUDED', 'Nao incluido na estatistica')], max_length=16, null=True)),
                ('new_status', models.CharField(choices=[('PENDING', 'Aguardando analise'), ('INCLUDED', 'Incluido na estatistica'), ('EXCLUDED', 'Nao incluido na estatistica')], max_length=16)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['changed_at'],
            },
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='has_source_update_after_statistics_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='source_update_after_statistics_review_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='statistics_exclusion_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='statistics_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='statistics_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_statistics_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='statistics_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='statistics_status',
            field=models.CharField(choices=[('PENDING', 'Aguardando analise'), ('INCLUDED', 'Incluido na estatistica'), ('EXCLUDED', 'Nao incluido na estatistica')], db_index=True, default='PENDING', max_length=16),
        ),
        migrations.AddIndex(
            model_name='inspectionreport',
            index=models.Index(fields=['statistics_status', 'operation_date'], name='inspection__statist_960de9_idx'),
        ),
        migrations.AddField(
            model_name='inspectionstatisticsdecisionhistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_statistics_decision_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspectionstatisticsdecisionhistory',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics_history', to='inspection.inspectionreport'),
        ),
    ]
