# Generated by Django 5.1.4 on 2026-08-12 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0002_inspectionstatisticsdecisionhistory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_report_id', models.UUIDField(db_index=True)),
                ('operation_date', models.DateField(db_index=True)),
                ('team', models.CharField(blank=True, db_index=True, max_length=120)),
                ('snapshot_source_updated_at', models.DateTimeField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(choices=[('REPORT', 'Relatorio')], db_index=True, default='REPORT', max_length=16)),
                ('operations_count', models.IntegerField()),
                ('approach', models.IntegerField(blank=True, null=True)),
                ('reconductor', models.IntegerField(blank=True, null=True)),
                ('refusal', models.IntegerField(blank=True, null=True)),
                ('celebrities_authorities', models.IntegerField(blank=True, null=True)),
                ('four_ml', models.IntegerField(blank=True, null=True)),
                ('thirtythree_ml', models.IntegerField(blank=True, null=True)),
                ('thirtyfour_ml', models.IntegerField(blank=True, null=True)),
                ('passive_tests_performed', models.IntegerField(blank=True, null=True)),
                ('cnh_collected', models.IntegerField(blank=True, null=True)),
                ('fined', models.IntegerField(blank=True, null=True)),
                ('towed', models.IntegerField(blank=True, null=True)),
                ('removal_resolutions', models.IntegerField(blank=True, null=True)),
                ('arrests_means_evidence', models.IntegerField(blank=True, null=True)),
                ('art307', models.IntegerField(blank=True, null=True)),
                ('criminal_occurrences', models.IntegerField(blank=True, null=True)),
                ('driving_canceled_license', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_inspection_statistics', to=settings.AUTH_USER_MODEL)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='official_statistic', to='inspection.inspectionreport')),
            ],
            options={
                'ordering': ['-operation_date', '-generated_at'],
                'indexes': [models.Index(fields=['operation_date', 'team'], name='inspection__operati_b75dd9_idx'), models.Index(fields=['source', 'operation_date'], name='inspection__source_8ec3c8_idx')],
            },
        ),
    ]
