# Generated by Django 5.1.4 on 2026-08-12 19:32

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0003_inspectionstatistic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionHistoricalImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file_name', models.CharField(max_length=255)),
                ('source_file_sha256', models.CharField(db_index=True, max_length=64, unique=True)),
                ('source_file_size', models.BigIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('COMPLETED', 'Concluido'), ('FAILED', 'Falhou'), ('PARTIAL', 'Parcial')], db_index=True, default='PENDING', max_length=16)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('rows_found', models.IntegerField(default=0)),
                ('rows_valid', models.IntegerField(default=0)),
                ('rows_imported', models.IntegerField(default=0)),
                ('rows_ignored', models.IntegerField(default=0)),
                ('errors_count', models.IntegerField(default=0)),
                ('warnings_count', models.IntegerField(default=0)),
                ('report_json', models.JSONField(blank=True, null=True)),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_historical_import_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionHistoricalStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_date', models.DateField(blank=True, db_index=True, null=True)),
                ('reference_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('reference_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('team', models.CharField(blank=True, db_index=True, max_length=120)),
                ('source_team_label', models.CharField(blank=True, max_length=160)),
                ('source_type', models.CharField(choices=[('DAILY', 'Diario'), ('ACCUMULATED', 'Acumulado'), ('LEGACY', 'Legado')], db_index=True, max_length=16)),
                ('source_sheet', models.CharField(max_length=120)),
                ('source_row', models.PositiveIntegerField()),
                ('taxonomy_era', models.CharField(choices=[('ERA_A', 'Era A'), ('ERA_B', 'Era B'), ('ERA_C', 'Era C')], db_index=True, max_length=16)),
                ('source_workbook_label', models.CharField(blank=True, max_length=255)),
                ('is_validation_only', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('fined', models.IntegerField(blank=True, null=True)),
                ('towed', models.IntegerField(blank=True, null=True)),
                ('refusal', models.IntegerField(blank=True, null=True)),
                ('cnh_collected', models.IntegerField(blank=True, null=True)),
                ('four_ml', models.IntegerField(blank=True, null=True)),
                ('thirtythree_ml', models.IntegerField(blank=True, null=True)),
                ('thirtyfour_ml', models.IntegerField(blank=True, null=True)),
                ('arrests_means_evidence', models.IntegerField(blank=True, null=True)),
                ('passive_tests_performed', models.IntegerField(blank=True, null=True)),
                ('reconductor', models.IntegerField(blank=True, null=True)),
                ('operations_count', models.IntegerField(blank=True, null=True)),
                ('removal_resolutions', models.IntegerField(blank=True, null=True)),
                ('driving_canceled_license', models.IntegerField(blank=True, null=True)),
                ('taxi_approached', models.IntegerField(blank=True, null=True)),
                ('taxi_illegal', models.IntegerField(blank=True, null=True)),
                ('planned_actions', models.IntegerField(blank=True, null=True)),
                ('rain', models.IntegerField(blank=True, null=True)),
                ('external_occurrence', models.IntegerField(blank=True, null=True)),
                ('public_security_occurrence', models.IntegerField(blank=True, null=True)),
                ('license_suspension', models.IntegerField(blank=True, null=True)),
                ('negative_tests', models.IntegerField(blank=True, null=True)),
                ('administrative_art_165', models.IntegerField(blank=True, null=True)),
                ('criminal_art_306', models.IntegerField(blank=True, null=True)),
                ('criminal_art_306_other_evidence', models.IntegerField(blank=True, null=True)),
                ('historical_alcohol_cases', models.IntegerField(blank=True, null=True)),
                ('historical_alcohol_percentage', models.DecimalField(blank=True, decimal_places=10, max_digits=12, null=True)),
                ('historical_event_trailers', models.IntegerField(blank=True, null=True)),
                ('historical_reconductors_licensed', models.IntegerField(blank=True, null=True)),
                ('historical_deliberations', models.IntegerField(blank=True, null=True)),
                ('historical_operations', models.IntegerField(blank=True, null=True)),
                ('historical_cnh_retained', models.IntegerField(blank=True, null=True)),
                ('historical_passive_tests', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='inspection.inspectionhistoricalimportbatch')),
            ],
            options={
                'ordering': ['-reference_date', '-reference_year', '-reference_month', 'team', 'source_sheet', 'source_row'],
                'indexes': [models.Index(fields=['reference_date', 'team'], name='inspection__referen_4fd341_idx'), models.Index(fields=['reference_year', 'reference_month'], name='inspection__referen_d9b375_idx'), models.Index(fields=['source_type', 'taxonomy_era'], name='inspection__source__40143a_idx'), models.Index(fields=['import_batch'], name='inspection__import__afe7d6_idx')],
                'constraints': [models.UniqueConstraint(fields=('import_batch', 'source_sheet', 'source_row'), name='uniq_inspection_historical_batch_sheet_row'), models.CheckConstraint(check=models.Q(('reference_date__isnull', True), ('reference_date__lte', datetime.date(2026, 8, 9)), _connector='OR'), name='inspection_historical_reference_date_cutoff')],
            },
        ),
    ]
