# Generated by Django 5.1.4 on 2026-08-12 19:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0004_inspectionhistoricalimportbatch_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionhistoricalimportbatch',
            name='source_type',
            field=models.CharField(blank=True, choices=[('DAILY', 'Diario'), ('ACCUMULATED', 'Acumulado'), ('LEGACY', 'Legado')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='inspectionhistoricalimportbatch',
            name='taxonomy_era',
            field=models.CharField(blank=True, choices=[('ERA_A', 'Era A'), ('ERA_B', 'Era B'), ('ERA_C', 'Era C')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='inspectionhistoricalimportbatch',
            name='source_file_sha256',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AddConstraint(
            model_name='inspectionhistoricalimportbatch',
            constraint=models.UniqueConstraint(fields=('source_file_sha256', 'source_type', 'taxonomy_era'), name='uniq_inspection_historical_batch_file_phase'),
        ),
    ]
