# Generated by Django 5.1.4 on 2026-08-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0005_inspectionhistoricalimportbatch_source_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionhistoricalstatistic',
            name='historical_approached',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectionhistoricalstatistic',
            name='historical_art_307',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
