# Generated by Django 5.1.4 on 2026-08-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0006_inspectionhistoricalstatistic_historical_approached_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionhistoricalstatistic',
            name='criminal_occurrences',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
