# Generated by Django 5.1.4 on 2026-08-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0007_historical_criminal_occurrences'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionPublicSecurityYearlyStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_year', models.PositiveSmallIntegerField(db_index=True, unique=True)),
                ('fugitives', models.IntegerField(blank=True, null=True)),
                ('flagrante', models.IntegerField(blank=True, null=True)),
                ('simulacrum', models.IntegerField(blank=True, null=True)),
                ('weapons', models.IntegerField(blank=True, null=True)),
                ('recovered_vehicles', models.IntegerField(blank=True, null=True)),
                ('narcotics', models.IntegerField(blank=True, null=True)),
                ('bribery', models.IntegerField(blank=True, null=True)),
                ('art311', models.IntegerField(blank=True, null=True)),
                ('art306', models.IntegerField(blank=True, null=True)),
                ('fake_cnh', models.IntegerField(blank=True, null=True)),
                ('suspended_cnh', models.IntegerField(blank=True, null=True)),
                ('canceled_cnh', models.IntegerField(blank=True, null=True)),
                ('source_label', models.CharField(blank=True, default='Serie historica de ocorrencias', max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estatistica anual de seguranca publica',
                'verbose_name_plural': 'Estatisticas anuais de seguranca publica',
                'ordering': ['reference_year'],
            },
        ),
    ]
