# Generated by Django 5.1.4 on 2026-08-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0008_inspectionpublicsecurityyearlystatistic'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionreport',
            name='statistics_classification',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
