# Generated by Django 5.1.4 on 2026-08-18 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0009_inspectionreport_statistics_classification'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=40, unique=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Regiao da Fiscalizacao',
                'verbose_name_plural': 'Regioes da Fiscalizacao',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InspectionMunicipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=120, unique=True)),
                ('normalized_name', models.CharField(db_index=True, max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='municipalities', to='inspection.inspectionregion')),
            ],
            options={
                'verbose_name': 'Municipio da Fiscalizacao',
                'verbose_name_plural': 'Municipios da Fiscalizacao',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['region', 'name'], name='inspection__region__1482f1_idx')],
            },
        ),
    ]
