# Generated by Django 5.1.4 on 2026-08-19 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0011_load_inspection_regions_municipalities'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionHistoricalTerritorialStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_date', models.DateField(db_index=True)),
                ('team', models.CharField(blank=True, db_index=True, max_length=120)),
                ('source_city', models.CharField(blank=True, max_length=255)),
                ('normalized_city', models.CharField(blank=True, max_length=255)),
                ('reports_count', models.IntegerField(default=0)),
                ('operations_count', models.IntegerField(default=0)),
                ('rain', models.IntegerField(default=0)),
                ('approach', models.IntegerField(default=0)),
                ('reconductor', models.IntegerField(default=0)),
                ('refusal', models.IntegerField(default=0)),
                ('fined', models.IntegerField(default=0)),
                ('towed', models.IntegerField(default=0)),
                ('cnh_collected', models.IntegerField(default=0)),
                ('four_ml', models.IntegerField(default=0)),
                ('thirtythree_ml', models.IntegerField(default=0)),
                ('thirtyfour_ml', models.IntegerField(default=0)),
                ('passive_tests_performed', models.IntegerField(default=0)),
                ('removal_resolutions', models.IntegerField(default=0)),
                ('arrests_means_evidence', models.IntegerField(default=0)),
                ('art307', models.IntegerField(default=0)),
                ('criminal_occurrences', models.IntegerField(default=0)),
                ('driving_canceled_license', models.IntegerField(default=0)),
                ('municipality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inspection.inspectionmunicipality')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inspection.inspectionregion')),
            ],
            options={
                'db_table': 'inspection_historical_territorial',
            },
        ),
    ]
