# Generated by Django 5.1.4 on 2026-09-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0012_inspectionhistoricalterritorialstatistic'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionreport',
            name='changes_material',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='civil_chief_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='complement_source_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='low_approach_reasons',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='military_chief_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='miscellaneous_changes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='specified_violation_notices',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='support_opm',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='support_pmerj_staff',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='support_vehicles',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='team_violation_notices',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
