# Generated by Django 6.0.4 on 2026-07-23 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedules', '0067_agenda_absent_designated_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsolidatedStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_date', models.DateField(blank=True, help_text='Obrigatório para SIED_OPERATIONAL', null=True)),
                ('reference_year', models.IntegerField(db_index=True)),
                ('reference_month', models.IntegerField(blank=True, null=True)),
                ('indicator_type', models.CharField(choices=[('AUDIENCE', 'Público'), ('ACTION', 'Ações'), ('MATERIAL', 'Materiais')], max_length=20)),
                ('category_entity_type', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.DecimalField(decimal_places=2, help_text='Quantidade consolidada (Público, Ações ou Materiais)', max_digits=12)),
                ('methodology', models.CharField(choices=[('HISTORICAL_LEGACY', 'Histórico Planilha (até 08/07/2026)'), ('SIED_OPERATIONAL', 'Operacional SIED (a partir de 09/07/2026)')], db_index=True, max_length=30)),
                ('traceability_id', models.CharField(db_index=True, help_text="Ex: 'legacy_2015_bares' ou 'report_5501'", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category_action_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedules.actiontype')),
            ],
            options={
                'verbose_name': 'Estatística Consolidada',
                'verbose_name_plural': 'Estatísticas Consolidadas',
                'ordering': ['-reference_year', '-reference_month'],
            },
        ),
        migrations.CreateModel(
            name='StatisticCategoryMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(help_text='Nome exato da coluna/categoria na planilha histórica', max_length=255, unique=True)),
                ('indicator_type', models.CharField(choices=[('AUDIENCE', 'Público'), ('ACTION', 'Ações'), ('MATERIAL', 'Materiais')], max_length=20)),
                ('sied_requester_entity', models.CharField(blank=True, help_text='Tipo de entidade solicitante (ex: ESCOLA PUBLICA)', max_length=255, null=True)),
                ('description', models.TextField(blank=True, help_text='Observações futuras sobre alterações de classificação histórica', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sied_action_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedules.actiontype')),
            ],
            options={
                'verbose_name': 'Mapeamento Histórico',
                'verbose_name_plural': 'Mapeamentos Históricos',
            },
        ),
    ]
