# Generated by Django 6.0.4 on 2026-07-23 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0068_educationreport_statistics_processed_and_more'),
        ('statistics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consolidatedstatistic',
            name='audit_history',
            field=models.JSONField(blank=True, default=list, help_text='Log de alterações de valores históricos'),
        ),
        migrations.AddField(
            model_name='consolidatedstatistic',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consolidatedstatistic',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consolidatedstatistic',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Ativo'), ('SUSPENDED', 'Suspenso'), ('CANCELLED', 'Cancelado')], db_index=True, default='ACTIVE', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='consolidatedstatistic',
            constraint=models.UniqueConstraint(fields=('traceability_id', 'indicator_type', 'category_action_type', 'category_entity_type'), name='unique_statistic_row'),
        ),
    ]
